scrumptious/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("admin/", admin.site.urls),
    path("recipes/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path("meal_plans/", include("meal_plans.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagListView,
    TagDetailView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView
)

urlpatterns = [
    path("", TagListView.as_view(), name="tags_list"),
    path("<int:pk>/", TagDetailView.as_view(), name="tag_detail"),
    path("new/", TagCreateView.as_view(), name="tag_new"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="tag_edit"),
    path("<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete")
]

tags/models.py
from django.db import models
from django.conf import settings
USER_MODEL = settings.AUTH_USER_MODEL


# Create your models here.
class Tag(models.Model):
    name = models.CharField(max_length=20)
    recipes = models.ManyToManyField("recipes.Recipe", related_name="tags")
    author = models.ForeignKey(USER_MODEL, related_name="tags", on_delete=models.CASCADE, null=True)
    updated_by = models.ForeignKey(USER_MODEL, related_name="tag_updates", on_delete=models.CASCADE, null=True)

tags/forms.py
from django import forms
from tags.models import Tag


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ["name", "recipes"]

tags/views.py
from django.shortcuts import render
from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView
from django.urls import reverse_lazy
from tags.models import Tag
from django.contrib.auth.mixins import LoginRequiredMixin



# Create your views here.
def show_tags(request):
    context = {
        "tags": Tag.objects.all() if Tag else None,
    }
    return render(request, "tags/list.html", context)


class TagListView(ListView):
    model = Tag
    template_name = "tags/list.html"
    paginate_by = 3

    def get_queryset(self):
        query = self.request.GET.get("q")
        if not query:
            query = ""
        return Tag.objects.filter(name__icontains=query)

    
class TagDetailView(DetailView):
    model = Tag
    template_name = "tags/detail.html"


class TagCreateView(LoginRequiredMixin, CreateView):
    model = Tag
    template_name = "tags/new.html"
    fields = ["name", "recipes"]
    success_url = reverse_lazy("tags_list")

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class TagUpdateView(LoginRequiredMixin, UpdateView):
    model = Tag
    template_name = "tags/edit.html"
    fields = ["name", "recipes"]
    success_url = reverse_lazy("tags_list")

    def form_valid(self, form):
        form.instance.updated_by = self.request.user
        return super().form_valid(form)


class TagDeleteView(LoginRequiredMixin, DeleteView):
    model = Tag
    template_name = "tags/delete.html"
    success_url = reverse_lazy("tags_list")

tags/templates/tags/delete.html
{% extends 'base.html' %}
{% load static %}
{% load markdownify %}

{% block content %}
    <main class="recipe-form">
        <form method="post">
          {% csrf_token %}
          <p>Are you sure you want to delete "{{ tag.name }}"?</p>
          {{ form.as_p }}
          <div class="control">
            <button class="button">Delete</button>
          </div>
        </form>
      </main>
{% endblock content %}

tags/templates/tags/detail.html
{% extends 'base.html' %}
{% load static %}
{% load markdownify %}


{% block content %}
        <main class="recipe-detail">
            <div>
              <a href="{% url 'tag_edit' tag.id %}">Edit</a>
              <a href="{% url 'tag_delete' tag.id %}">Delete</a>
            </div>
            <h1>{{ tag.name }}</h1>
            <h2>by: {{ tag.author | default_if_none:"Unknown"}}</h2>
            <h3>updated by: {{ tag.updated_by | default_if_none:"No updates yet"}} </h3>
            <p>Recipe(s): {% for recipe in tag.recipes.all %}{{ recipe.name }},  {% endfor %}</p>
        </main>
{% endblock content %}

tags/templates/tags/edit.html
{% extends 'base.html' %}

{% load static %}
{% load markdownify %}

{% block content %}
    <main class="recipe-form">
        <form method="post">
          {% csrf_token %}
          {{ form.as_p }}
          <div class="control">
            <button class="button">Update</button>
          </div>
        </form>
    </main>
{% endblock content %}

tags/templates/tags/list.html
{% extends 'paginate.html' %}

{% block content %}
  <main class="recipe-grid">
    <p>
      <form method="GET">
        <input type="text" name="q">
        <button type="submit">Search</button>
      </form>
    </p>
    {% for tag in tag_list %}
      <div class="recipe-card">
        <h2 class="recipe-card-title">
          <a href="{% url 'tag_detail' tag.pk %}">{{ tag.name }}</a>
        </h2>
        <p class="recipe-card-date">{{ tag.updated }}</p>
      </div>
    {% endfor %}
  </main>
{% endblock content %}

tags/templates/tags/new.html
{% extends 'base.html' %}

{% load static %}
{% load markdownify %}
{% block content %}
        <main class="recipe-form">
            <form method="post">
              {% csrf_token %}
              {{ form.as_p }}
              <div class="control">
                <button class="button">Create Tag</button>
              </div>
            </form>
          </main>
{% endblock content %}