meal_plans/urls.py
from django.urls import path
from meal_plans.views import (
    MealPlanListView,
    MealPlanCreateView,
    MealPlanDetailView,
    MealPlanUpdateView,
    MealPlanDeleteView
)

urlpatterns = [
    path("", MealPlanListView.as_view(), name="meal_plans_list"),
    path("new/", MealPlanCreateView.as_view(), name="meal_plan_new"),
    path("<int:pk>/", MealPlanDetailView.as_view(), name="meal_plan_detail"),
    path("<int:pk>/edit/", MealPlanUpdateView.as_view(), name="meal_plan_edit"),
    path("<int:pk>/delete/", MealPlanDeleteView.as_view(), name="meal_plan_delete")
]

scrumptious/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
    path("admin/", admin.site.urls),
    path("recipes/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path("meal_plans/", include("meal_plans.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagListView,
    TagDetailView,
    TagCreateView,
    TagUpdateView,
    TagDeleteView
)

urlpatterns = [
    path("", TagListView.as_view(), name="tags_list"),
    path("<int:pk>/", TagDetailView.as_view(), name="tag_detail"),
    path("new/", TagCreateView.as_view(), name="tag_new"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="tag_edit"),
    path("<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete")
]

meal_plans/models.py
from django.db import models
from django.conf import settings
from recipes.models import Recipe

USER_MODEL = settings.AUTH_USER_MODEL


# Create your models here.

class MealPlan(models.Model):
    name = models.CharField(max_length=120)
    date = models.DateTimeField()
    owner = models.ForeignKey(USER_MODEL, related_name="meal_plans", on_delete=models.CASCADE, null=True)
    recipes = models.ManyToManyField("recipes.Recipe", related_name="recipes")

meal_plans/views.py
from django.shortcuts import render, redirect
from meal_plans.models import MealPlan
from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin, AccessMixin
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from django.urls import reverse_lazy
from django.db import models


# Create your views here.

class MealPlanListView(LoginRequiredMixin, ListView):
    model = MealPlan
    template_name = "meal_plans/list.html"
    paginate_by = 4

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)


class MealPlanCreateView(LoginRequiredMixin, CreateView):
    model = MealPlan
    template_name = "meal_plans/new.html"
    fields = ["name", "date", "recipes"]
    success_url = reverse_lazy("meal_plans_list")

    def form_valid(self, form):
        plan = form.save(commit=False)
        plan.owner = self.request.user
        plan.save()
        form.save_m2m()
        return redirect("meal_plan_detail", pk=plan.id)


class MealPlanDetailView(LoginRequiredMixin, DetailView):
    model = MealPlan
    template_name = "meal_plans/detail.html"

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)


class MealPlanUpdateView(LoginRequiredMixin, UpdateView):
    model = MealPlan
    template_name = "meal_plans/edit.html"
    fields = ["name", "date", "recipes"]
    success_url = reverse_lazy("meal_plan_detail")

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)

    def form_valid(self, form):
        plan = form.save(commit=False)
        plan.owner = self.request.user
        plan.save()
        form.save_m2m()
        return redirect("meal_plan_detail", pk=plan.id)


class MealPlanDeleteView(LoginRequiredMixin, DeleteView):
    model = MealPlan
    template_name = "meal_plans/delete.html"
    success_url = reverse_lazy("meal_plans_list")
    
    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)

meal_plans/templates/meal_plans/delete.html
{% extends 'base.html' %}


{% block content %}
<main class="recipe-form">
    <h2>Woah!</h2>
    <form method="post">
      {% csrf_token %}
      <p>Are you sure you want to delete "{{ mealplan.name }}"?</p>
      {{ form.as_p }}
      <div class="control">
        <button class="button">Delete</button>
      </div>
    </form>
  </main>
{% endblock content %}

meal_plans/templates/meal_plans/detail.html
{% extends 'base.html' %}
{% load markdownify %}


{% block content %}
<main class="plan-detail">
    <div>
      <a href="{% url 'meal_plan_edit' mealplan.id %}">Edit</a>
      <a href="{% url 'meal_plan_delete' mealplan.id %}">Delete</a>
    </div>
    <h1>{{ mealplan.name }}</h1>
    <h2>by: {{ mealplan.owner | default_if_none:"Unknown" }}
    <h2>next meal: {{ mealplan.date | default_if_none:"No date" }}

    <p>Included recipes: {% for recipe in mealplan.recipes.all %}{{ recipe.name }},  {% endfor %}</p>
  </main>
{% endblock content %}

meal_plans/templates/meal_plans/edit.html
{% extends 'base.html' %}


{% block content %}
<main class="recipe-form">
    <h2>Edit {{ mealplan.name }}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="control">
            <button class="button">Submit</button>
        </div>
    </form>
</main> 
{% endblock content %}

meal_plans/templates/meal_plans/list.html
{% extends 'paginate.html' %}
{% load markdownify %}


{% block content %}
    <main>
        <div class="create-link">
            <a href="{% url 'meal_plan_new' %}">Create meal plan</a>
        </div>
        <div class="recipe-grid">
            {% for mealplan in mealplan_list %}
                <div class="plan-card">
                    <h2 class="recipe-card-title">
                    <a href="{% url 'meal_plan_detail' mealplan.pk %}">{{ mealplan.name }}</a>
                    </h2>
                    {% for recipe in mealplan.recipes.all %}
                        <li>{{ recipe.name }}</li>
                </div>
                    {% endfor %}
            {% endfor %}
        </div>
    </main>
{% endblock content %}

meal_plans/templates/meal_plans/new.html
{% extends 'base.html' %}


{% block content %}
    <main class="recipe-form">
        <h2>Create Meal Plan</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="control">
                <button class="button">Submit</button>
            </div>
        </form>
    </main> 
{% endblock content %}


{% comment %} <main class="recipe-form">
    <form method="post">
      {% csrf_token %}
      {{ form.as_p }}
      <div class="control">
        <button class="button">Create</button>
      </div>
    </form>
  </main> {% endcomment %}